---
- hosts: local
  become: yes
  vars:
    app_name: Alfred 4
    app_url: https://cachefly.alfredapp.com/Alfred_4.1_1167.dmg
    installer_type: app
    download_file_type: dmg
    install_method: dmg
  roles: 
    - setup
    - installer
    - cleanup
   