---
- hosts: local
  become: yes
  vars:
    app_name: Docker
    app_url: https://download.docker.com/mac/stable/Docker.dmg
    installer_type: app
    download_file_type: dmg
    install_method: dmg
  roles: 
    - setup
    - installer
    - cleanup
   