---
- hosts: local
  become: yes
  vars:
    app_name: draw.io
    app_url: https://github.com/jgraph/drawio-desktop/releases/download/v13.5.1/draw.io-13.5.1.dmg
    installer_type: app
    download_file_type: dmg
    install_method: dmg
  roles: 
    - setup
    - installer
    - cleanup
   