---
- hosts: local
  become: yes
  vars:
    app_name: IINA
    app_url: https://dl.iina.io/IINA.v1.0.7.dmg
    installer_type: app
    download_file_type: dmg
    install_method: dmg
  roles: 
    - setup
    - installer
    - cleanup
   